# Generated by Django 3.0.2 on 2020-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('GABINETE', 'GABINETE'), ('PROCESSADOR', 'PROCESSADOR'), ('PLACA-MAE', 'PLACA-MAE'), ('MEMORIA', 'MEMORIA'), ('HD', 'HD'), ('SSD', 'SSD'), ('COOLER', 'COOLER'), ('FONTE', 'FONTE'), ('DISPLAY', 'DISPLAY'), ('OUTROS', 'OUTROS')], max_length=50, verbose_name='Categoria')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('preco', models.FloatField(verbose_name='Preco')),
                ('aceita_cartao', models.BooleanField(default=True, verbose_name='Aceita cartao')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['modelo'],
            },
        ),
    ]
