# Generated by Django 3.0.2 on 2020-02-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200220_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default='default descricao', verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img2',
            field=models.ImageField(default='default descricao', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img3',
            field=models.ImageField(default='default descricao', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img4',
            field=models.ImageField(default='default descricao', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='img5',
            field=models.ImageField(default='default descricao', upload_to='images/'),
            preserve_default=False,
        ),
    ]
