# Generated by Django 3.0.3 on 2020-03-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default='teste', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
