# Generated by Django 3.0.3 on 2020-03-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_auto_20200309_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img3',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img4',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img5',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
