# Generated by Django 3.0.3 on 2020-03-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_auto_20200318_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='create_at',
            field=models.DateField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='updated_at',
            field=models.DateField(verbose_name='Atualizado em'),
        ),
    ]
