# Generated by Django 3.0.3 on 2020-03-28 18:14

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0010_favorito'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='favorito',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
