# Generated by Django 3.0.3 on 2020-03-31 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_auto_20200329_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='img',
            new_name='img1',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='img5',
        ),
    ]
