# Generated by Django 3.0.3 on 2020-04-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_auto_20200331_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['marca_modelo'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='modelo',
        ),
        migrations.AddField(
            model_name='produto',
            name='marca_modelo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo ou Marca'),
        ),
    ]
