# Generated by Django 3.0.3 on 2020-04-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0015_auto_20200401_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img1',
            field=models.CharField(max_length=100, null=True, verbose_name='img1'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img2',
            field=models.CharField(max_length=100, null=True, verbose_name='img2'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img3',
            field=models.CharField(max_length=100, null=True, verbose_name='img3'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img4',
            field=models.CharField(max_length=100, null=True, verbose_name='img4'),
        ),
    ]
