# Generated by Django 2.2.7 on 2020-01-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_usermore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermore',
            name='endereco',
        ),
    ]
