# Generated by Django 3.0.3 on 2020-02-28 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200120_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bairro',
            field=models.CharField(default='padrao', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='num_rua',
            field=models.IntegerField(default=666),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='rua',
            field=models.CharField(default='beco diagonal', max_length=100),
            preserve_default=False,
        ),
    ]
