# Generated by Django 3.0.3 on 2020-03-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200227_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMore',
        ),
    ]
