# Generated by Django 3.0.3 on 2020-03-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200318_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='num_rua',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rua',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
