# Generated by Django 3.0.3 on 2020-03-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200328_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
