# Generated by Django 3.0.3 on 2020-04-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar',
            field=models.CharField(max_length=100, verbose_name='avatar'),
        ),
    ]
